# malice/bitdefender plugin configuration.

name = 'bitdefender'
description = 'Malice Bitdefender AntiVirus'
category = 'av'
version = '0.1.0'

accepts = [ '*' ]

[system]
cpu = 0.5
ram = 256 # MB

[settings]
