version: '3'
services:
  elasticsearch:
    image: malice/elasticsearch:6.3

  app:
    build:
      context: .
    links:
     - elasticsearch
    image: app
    environment:
      - MALICE_ELASTICSEARCH=elasticsearch
    command: -V -t EICAR
