# malice/fileinfo plugin configuration.

name = 'fileinfo'
description = 'Malice File Info Plugin (exiftool, TRiD and ssdeep)'
category = 'metadata'
version = '0.1.0'

accepts = [ '*' ]

[system]
cpu = 0.5
ram = 256 # MB

[settings]
